import type { Metadata } from "next";
import { Abhaya_Libre } from "next/font/google";
import "./globals.css";

const abhaya = Abhaya_Libre({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-abhaya-libre",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${abhaya.variable} antialiased`}>{children}</body>
    </html>
  );
}
