import type { Metadata } from "next";
import { Abhaya_Libre, Beau_Rivage, Ephesis, Cinzel } from "next/font/google";
import "./globals.css";

const abhaya = Abhaya_Libre({
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-abhaya-libre",
  subsets: ["latin"],
});

const beau = Beau_Rivage({
  weight: ["400"],
  variable: "--font-beau-rivage",
  subsets: ["latin", "latin-ext", "vietnamese"]
})

const ephesis = Ephesis({
  weight: ["400"],
  variable: "--font-ephesis",
  subsets: ["latin", "latin-ext", "vietnamese"]
})

const cinzel = Cinzel({
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-cinzel",
  subsets: ["latin", "latin-ext"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${abhaya.variable} ${beau.variable} ${ephesis.variable} ${cinzel.variable} antialiased`}>{children}</body>
    </html>
  );
}
